services:
  drfhello:
    image: myapp-oci-image:0.0.1
    volumes:
      - ./:/home/app_user
    ports:
      - 8000:8000
    restart: always
    env_file:
      .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17.0-alpine3.20
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432      
    env_file:
      .env      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 9s
      retries: 60

volumes:
  postgres_data:
