from pylatex import Command, Document, Math, Section, Tabular, VerticalSpace
from pylatex.utils import NoEscape, bold


def generate_report():
    doc = Document(geometry_options={"margin": "2.5cm"})

    doc.preamble.append(Command("title", "Powers Report"))
    doc.preamble.append(Command("author", "Generated by PyLaTeX"))
    doc.preamble.append(Command("date", NoEscape(r"\today")))
    doc.append(NoEscape(r"\maketitle"))

    with doc.create(Section("Introduction")):
        doc.append("This report was generated using ")
        doc.append(bold("PyLaTeX"))
        doc.append(
            ", a Python library for creating LaTeX documents programmatically."
        )

    with doc.create(Section("Powers Table")):
        doc.append("Powers of integers from 1 to 10:")
        doc.append(VerticalSpace("0.5em"))

        with doc.create(Tabular("r r r r")) as table:
            table.add_hline()
            table.add_row(
                [
                    bold("n"),
                    bold(NoEscape(r"$n^2$")),
                    bold(NoEscape(r"$n^3$")),
                    bold(NoEscape(r"$n^4$")),
                ]
            )
            table.add_hline()
            for i in range(1, 11):
                table.add_row([i, i**2, i**3, i**4])
            table.add_hline()

    with doc.create(Section("Formula")):
        doc.append("The general formula for integer powers:")
        with doc.create(Math()):
            doc.append(
                NoEscape(r"a^n = \underbrace{a \cdot a \cdots a}_{n \text{ times}}")
            )

    return doc.dumps()


def start():
    print(generate_report())
