name: Nix Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - macos-13

    steps:
      - name: Metadata about the runs-on machine
        run: |
          uname -a
          cat /etc/os-release || true
          cat /etc/lsb-release || true
          cat /proc/cpuinfo || true
          cat /proc/meminfo || true
          df -h || true
          free -h || true
          nproc || true
          lscpu || true
          sysctl -a || true
          sysctl -a | grep -i mem || true
          sysctl -a | grep -i cpu || true
          sysctl -a | grep -i vm || true
          sysctl -a | grep -i sched || true
          sysctl -a | grep -i numa || true

      - name: Run 
        run: |
          curl -L https://hydra.nixos.org/job/nix/master/buildStatic.nix.$(uname -m)-linux/latest/download-by-type/file/binary-dist > nix \
          && chmod +x nix \
          && ./nix --version \
          && ./nix \
                --extra-experimental-features nix-command \
                --extra-experimental-features flakes \
                build \
                --print-build-logs \
                nixpkgs#hello

      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Run Nix Build
        run: |
          nix flake --version
          nix flake metadata nixpkgs
          nix build --print-build-logs nixpkgs#pkgsStatic.hello
