name: tests

on: workflow_dispatch
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branchs:
#       - 'feature/**'
#       - 'fix/**'
#       - 'refactor/**'


jobs:
  test:
    runs-on: arc-runner-set
    # runs-on:
    #   labels: nixos
    # runs-on: self-hosted
    name: Testes
    steps:
      - name: checkout PR merge commit
        uses: actions/checkout@v4

      - name: Executa um echo
        run: echo 'Olá mundo!'

      - name: Host metadata
        run: |
          cat /etc/os*release
          # cat /etc/group
          uname -a
          id
          pwd
          ls -alh
          nproc
          free -h
          # sudo id
          cat $HOME/logs.txt || true
          echo FOO-BAR > $HOME/logs.txt

      - name: Testes sobre docker
        run: |
          # env | sort
          # touch /dev/kvm
          # which docker
          # readlink -f $(which docker)
          docker --version
          # sudo docker info
          docker info
          sleep 1000000
          docker images
          docker run --rm alpine cat /etc/os-release
          docker images

      - name: Testes sobre docker build
        run: |
          id
          docker build --tag custom-python .
          docker images

      - name: Testes sobre /dev/kvm
        run: |
          id
          docker run --privileged=true --rm \
          alpine sh -c 'id && touch /dev/kvm && stat /dev/kvm'

      - name: Nix metadata
        run: |
           nix flake --version
           nix flake metadata nixpkgs
           nix run nixpkgs#nix-info -- --markdown
